### ISSUE TITLE
Fully Functional CRUD project categories

### ISSUE THREAD

**Issue by stv2pointo** [CS4790F17/HfH-Team-Resources#79]

**Comment by blake1991** [comment]
Admin can add project categories on the manage project page. For some unexplained reason that partial view returns incredibly slowly. They can't, however, remove or edit categories.

**Comment by blake1991** [comment]
Starting on branch https://github.com/CS4790F17/HfH-Team-Resources/tree/Feature/ProjectCategoryCRUD

**Comment by blake1991** [comment]
Opened pull request for review. #88

**Comment by stv2pointo** [comment]
merged
