### ISSUE TITLE
Event model addition

### ISSUE THREAD

**Issue by stv2pointo** [CS4790F17/HfH-Team-Resources#84]
For the purpose of obtaining more grants, HfH needs to be able to track data for "Events". An event is related to certain projects over a certain time period. An event can have zero, one, or many projects. An event has a name, a start date, and an end date. A project can have a relationship to zero, one, or many events. Organizations and Volunteers can have a relationship to zero, one, or many Events through their tracked timeSheets. This will require full CRUD capability for an Event model, the ability to connect projects to events, and the ability to view data relevant to an event.  Specific data requirements are pending.

**Comment by stv2pointo** [comment]
From an email 12/817:
Could you help me to understand more about Events? I'm currently looking at how to implement it in the site and am curious if I'm barking up the right tree. Any clarification you could provide would be helpful for me to meet your needs.

The way I understand it,
·       An Event can have a relationship to zero, one, or many Projects
·       A Project could possibly have a relationship to zero, one, or many Events
·       An Organization can possibly have a relationship to zero, one or many Events through the Volunteers that participate.
·       A Volunteer can possibly have a relationship to zero, one, or many Events through their logged time on one or more of the Projects associated with an Event

An Event has
·       A name
·       A description
·       A start and end date
·       Projects (from any Project Category)
·       Maybe a partner or promoter?
An Event report has
·       Count of Volunteers
·       Count of Volunteer Hours
·       Count by Gender
·       Count of New Volunteers and their hours
·       Count disadvantaged youth (please define how this is determined, perhaps which income brackets?)
·       Count college students
·       Count Baby boomers (Is this based on DOB 1940 – 1960 ??)
·       Count Disabled
·       Count Veterans
·       Does this report need other demographic info such as ethnicity?

I’m picturing an Events page, where you can create, view, and update Events. This page would also list all Events and provide links to pages with the information and report about each Event. Please let me know what I have right and what I have wrong.

Thanks,
Steve

Response:
This is correct. 
The event for 9/11 consisted of projects that occurred throughout the weeks (I think this actually included the 8/30/2017 event and went as far as 9/21/2017) associated with it. For the grant, they wanted to know demographics associated with the volunteers that attended. They wanted to include ethnicity, but we had not tracked it at the time and were unable to include it.
For the MLK event, we will potentially be doing something on the 13th and 20th of January, and would need to answer to the same sort of information requests regarding volunteers, hours, and demographics.
I do not see anything you have wrong. I hope this makes sense.

**Comment by stv2pointo** [comment]
@blake1991 This is very similar to a category. I'm thinking we can add a foreign key to Project to link it to Event. Does that sound right to you?

**Comment by stv2pointo** [comment]
Maybe not, if a Project could be a part of multiple events, such as ReStore, it would need a many to many relationship

**Comment by blake1991** [comment]
The way I see it an Event has Projects. You would need an Event table linked to some EventProject table linked to the Project table.

**Comment by stv2pointo** [comment]
The basics of listing events and crud for them is there. Doing reports on it will be in another task. Close issue when satisfied and [merge PR](https://github.com/CS4790F17/HfH-Team-Resources/pull/87). Create, Edit, and Delete can be moved into modals later to match the rest of the project. I'm thinking that adding and removing Projects to an Event is best left the way it is, rather than squeeze it into a modal.
